name: Whoop Calendar Sync

on:
  schedule:
    # Run every 6 hours (at 00:00, 06:00, 12:00, 18:00 UTC)
    - cron: '0 */6 * * *'
  workflow_dispatch: # Allow manual trigger
  push:
    branches: [ main ]

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        pip install requests google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client
        
    - name: Create credentials file
      run: |
        echo '${{ secrets.GOOGLE_CREDENTIALS }}' > credentials.json
        
    - name: Create token file
      run: |
        echo '${{ secrets.GOOGLE_TOKEN }}' | base64 -d > token.pickle
        
    - name: Create Whoop token file
      run: |
        echo '${{ secrets.WHOOP_TOKEN }}' > whoop_token.json
        
    - name: Run sync
      run: |
        python sync.py --days 1
      env:
        WHOOP_CLIENT_ID: ${{ secrets.WHOOP_CLIENT_ID }}
        WHOOP_CLIENT_SECRET: ${{ secrets.WHOOP_CLIENT_SECRET }}
        
    - name: Upload logs
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: sync-logs
        path: |
          sync.log
          synced_workouts.json
          synced_sleep.json
        if-no-files-found: warn 